sudo: false
language: python
cache:
  directories:
  - "~/.cache/pip"
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"
- "3.7"
- "pypy"
env:
- HTML5LIB=0.99999999   # 8
- HTML5LIB=0.999999999  # 9
- HTML5LIB=1.0b10
- HTML5LIB=1.0.1
install:
  # html5lib 0.99999999 (8 9s) requires at least setuptools 18.5
  - pip install -U pip setuptools>=18.5
  - pip install -r requirements-dev.txt
  # stomp on html5lib install with the specified one
  - pip install html5lib==$HTML5LIB
script:
- py.test
- flake8 bleach/
deploy:
  provider: pypi
  user: jezdez
  distributions: sdist bdist_wheel
  password:
    secure: TTLpnNBAmRBPe4qITwtM6MRXw3CvGpflnkG6V97oKYL1RJhDXmxIxxImkGyVoT2IR4Oy/jqEikWUCCC3aDoqDnIkkDVriTPmo5PGnS2WgvEmYdcaTIp+RXdKwKhpCVX8ITEuye0iCXYu28vDaySGjnxjlYAP4S0PGPUzh/tn4DY=
  on:
    tags: true
    repo: mozilla/bleach
    python: "2.7"
