sudo: false
language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
install: 
  - "pip install -r requirements.txt"
script:
 - nosetests
 - nosetests suffix_update.py
 - flake8 bleach/ suffix_update.py
