language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "pypy"
install: 
 - "pip install git+git://github.com/marcdm/html5lib-python.git#egg=html5lib"
 - "pip install -r requirements.txt --use-mirrors"
script: nosetests
